CREATE PROC FI_SP_AltBeneficiario
	@ID             BIGINT,
    @CPF			VARCHAR(11),
	@NOME           VARCHAR (50) 
	
AS
BEGIN
	UPDATE BENEFICIARIOS
	SET 
		NOME = @NOME, 
		CPF = @CPF
	WHERE ID = @ID
END